kind: pipeline
clone:
  disable: true

steps:
  - name: feishu
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/foo-webhook
    settings:
      webhook:
        from_secret: webhook
      secret:
        from_secret: secret
      text: hello
  - name: clone
    image: alpine/git
    environment:
      warehouse_name: dekopon-design
    commands:
      - echo $DRONE_COMMIT_BRANCH
      - echo $DRONE_GIT_SSH_URL
      - ls /root/.ssh/
      - chmod -R 600 /root/.ssh/
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - git clone -b $DRONE_COMMIT_BRANCH --depth=1 $DRONE_GIT_SSH_URL
      - cd $warehouse_name
      - pwd
      - mv -f * .[^.]* /drone/src
      - ls

  - name: build
    image: go:lts
    depends_on: [clone]
    commands:
      - pwd
      - ls -a
      - make docker
  - name: deploy
    image: appleboy/drone-scp
    depends_on: [build]
    settings:
      host:
        from_secret: host
      port: 22
      username:
        from_secret: username
      password:
        from_secret: password
      target: /root
      source: ./dist
